-- MySQL Script generated by MySQL Workbench
-- Wed Jun 24 20:42:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vladanje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vladanje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vladanje` (
  `idVladanja` INT(10) NOT NULL,
  `ocenaVladanja` INT(1) NOT NULL DEFAULT 5,
  `opisVladanja` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idVladanja`),
  UNIQUE INDEX `idVladanja_UNIQUE` (`idVladanja` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Grad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Grad` (
  `ptt` INT(10) NOT NULL,
  `nazivGrada` VARCHAR(40) NOT NULL,
  `nazivDrzave` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ptt`),
  UNIQUE INDEX `ptt_UNIQUE` (`ptt` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Osoba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Osoba` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Osoba` (
  `jmbg` INT(13) NOT NULL,
  `ime` VARCHAR(20) NOT NULL,
  `prezime` VARCHAR(20) NOT NULL,
  `pol` VARCHAR(1) NOT NULL,
  `datumRodjenja` DATE NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `email` VARCHAR(30) NULL,
  `telefon` INT(30) NULL,
  `ptt` INT(10) NOT NULL,
  PRIMARY KEY (`jmbg`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC),
  INDEX `ptt_idx` (`ptt` ASC),
  UNIQUE INDEX `jmbg_UNIQUE` (`jmbg` ASC),
  CONSTRAINT `ptt`
    FOREIGN KEY (`ptt`)
    REFERENCES `mydb`.`Grad` (`ptt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Roditelj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roditelj` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roditelj` (
  `jmbgRoditelja` INT(13) NOT NULL,
  `zanimanje` VARCHAR(30) NULL,
  PRIMARY KEY (`jmbgRoditelja`),
  UNIQUE INDEX `jmbgRoditelja_UNIQUE` (`jmbgRoditelja` ASC),
  CONSTRAINT `jmbgRoditelja`
    FOREIGN KEY (`jmbgRoditelja`)
    REFERENCES `mydb`.`Osoba` (`jmbg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Skola`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Skola` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Skola` (
  `idSkole` INT(10) NOT NULL,
  `nazivSkole` VARCHAR(45) NOT NULL,
  `tipSkole` VARCHAR(45) NOT NULL,
  `nivoSkole` VARCHAR(45) NOT NULL,
  `ptt` INT(10) NOT NULL,
  PRIMARY KEY (`idSkole`),
  INDEX `ptt_idx` (`ptt` ASC),
  UNIQUE INDEX `ptt_UNIQUE` (`ptt` ASC),
  UNIQUE INDEX `idSkole_UNIQUE` (`idSkole` ASC),
  CONSTRAINT `ptt2`
    FOREIGN KEY (`ptt`)
    REFERENCES `mydb`.`Grad` (`ptt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Odeljenje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Odeljenje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Odeljenje` (
  `idOdeljenja` INT(10) NOT NULL,
  `nazivOdeljenja` VARCHAR(20) NOT NULL,
  `razred` INT(1) NOT NULL,
  `idSkole` INT(10) NOT NULL,
  PRIMARY KEY (`idOdeljenja`),
  INDEX `idSkole_idx` (`idSkole` ASC),
  UNIQUE INDEX `idOdeljenja_UNIQUE` (`idOdeljenja` ASC),
  UNIQUE INDEX `idSkole_UNIQUE` (`idSkole` ASC),
  CONSTRAINT `idSkole`
    FOREIGN KEY (`idSkole`)
    REFERENCES `mydb`.`Skola` (`idSkole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Nastavnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nastavnik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nastavnik` (
  `jmbgNastavnika` INT(13) NOT NULL,
  `zvanje` VARCHAR(30) NOT NULL,
  `idOdeljenja` INT(10) NOT NULL,
  PRIMARY KEY (`jmbgNastavnika`),
  INDEX `idOdeljenja_idx` (`idOdeljenja` ASC),
  UNIQUE INDEX `jmbgNastavnika_UNIQUE` (`jmbgNastavnika` ASC),
  CONSTRAINT `jmbgRoditelja2`
    FOREIGN KEY (`jmbgNastavnika`)
    REFERENCES `mydb`.`Osoba` (`jmbg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOdeljenja`
    FOREIGN KEY (`idOdeljenja`)
    REFERENCES `mydb`.`Odeljenje` (`idOdeljenja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Predmet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Predmet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Predmet` (
  `idPredmeta` INT NOT NULL,
  `brojCasova` INT(2) NOT NULL,
  `pismeniDeo` VARCHAR(45) NOT NULL,
  `usmeniDeo` VARCHAR(45) NOT NULL,
  `vannastavneAktivnosti` VARCHAR(45) NULL,
  `literature` VARCHAR(45) NOT NULL,
  `jmbgNastavnika` INT(13) NOT NULL,
  PRIMARY KEY (`idPredmeta`),
  INDEX `jmbgNastavnika_idx` (`jmbgNastavnika` ASC),
  UNIQUE INDEX `idPredmeta_UNIQUE` (`idPredmeta` ASC),
  UNIQUE INDEX `jmbgNastavnika_UNIQUE` (`jmbgNastavnika` ASC),
  CONSTRAINT `jmbgNastavnika`
    FOREIGN KEY (`jmbgNastavnika`)
    REFERENCES `mydb`.`Nastavnik` (`jmbgNastavnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Smer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Smer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Smer` (
  `idSmera` INT(10) NOT NULL,
  `nazivSmera` VARCHAR(45) NOT NULL,
  `idSkole` INT(10) NOT NULL,
  PRIMARY KEY (`idSmera`),
  INDEX `idSkole_idx` (`idSkole` ASC),
  UNIQUE INDEX `idSmera_UNIQUE` (`idSmera` ASC),
  UNIQUE INDEX `idSkole_UNIQUE` (`idSkole` ASC),
  CONSTRAINT `idSkole2`
    FOREIGN KEY (`idSkole`)
    REFERENCES `mydb`.`Skola` (`idSkole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Ucenik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ucenik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ucenik` (
  `jmbgUcenika` INT(13) NOT NULL,
  `idVladanja` INT(10) NOT NULL,
  `idOdeljenja` INT(10) NOT NULL,
  `idSmera` INT(10) NOT NULL,
  PRIMARY KEY (`jmbgUcenika`),
  INDEX `idVladanja_idx` (`idVladanja` ASC),
  INDEX `idOdeljenja_idx` (`idOdeljenja` ASC),
  INDEX `idSmera_idx` (`idSmera` ASC),
  UNIQUE INDEX `jmbgUcenika_UNIQUE` (`jmbgUcenika` ASC),
  CONSTRAINT `jmbgUcenika`
    FOREIGN KEY (`jmbgUcenika`)
    REFERENCES `mydb`.`Osoba` (`jmbg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVladanja`
    FOREIGN KEY (`idVladanja`)
    REFERENCES `mydb`.`Vladanje` (`idVladanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOdeljenja2`
    FOREIGN KEY (`idOdeljenja`)
    REFERENCES `mydb`.`Odeljenje` (`idOdeljenja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSmera`
    FOREIGN KEY (`idSmera`)
    REFERENCES `mydb`.`Smer` (`idSmera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`JeDete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JeDete` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JeDete` (
  `jmbgRoditelja` INT(13) NOT NULL,
  `jmbgUcenika` INT(13) NOT NULL,
  INDEX `jmbgUcenika_idx` (`jmbgUcenika` ASC) ,
  UNIQUE INDEX `jmbgRoditelja_UNIQUE` (`jmbgRoditelja` ASC) ,
  UNIQUE INDEX `jmbgUcenika_UNIQUE` (`jmbgUcenika` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`DobioOcenu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DobioOcenu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DobioOcenu` (
  `ocena` INT(1) NOT NULL,
  `datum` DATE NOT NULL,
  `jmbgUcenika` INT(13) NOT NULL,
  `idPredmeta` INT(10) NOT NULL,
  INDEX `jmbgUcenika_idx` (`jmbgUcenika` ASC),
  INDEX `idPredmeta_idx` (`idPredmeta` ASC),
  PRIMARY KEY (`idPredmeta`, `jmbgUcenika`),
  UNIQUE INDEX `ocena_UNIQUE` (`ocena` ASC),
  UNIQUE INDEX `idPredmeta_UNIQUE` (`idPredmeta` ASC),
  UNIQUE INDEX `jmbgUcenika_UNIQUE` (`jmbgUcenika` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Pohadja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pohadja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pohadja` (
  `brojPrisustva` INT(5) NOT NULL,
  `brojOdsustva` INT(5) NOT NULL,
  `brojOpravdanja` INT(5) NOT NULL,
  `jmbgUcenika` INT(13) NOT NULL,
  `idPredmeta` INT(10) NOT NULL,
  PRIMARY KEY (`idPredmeta`, `jmbgUcenika`),
  INDEX `jmbgUcenika_idx` (`jmbgUcenika` ASC),
  UNIQUE INDEX `idPredmeta_UNIQUE` (`idPredmeta` ASC),
  UNIQUE INDEX `jmbgUcenika_UNIQUE` (`jmbgUcenika` ASC))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Adding data to tables
-- -----------------------------------------------------

INSERT INTO `mydb`.`Vladanje` VALUES (223, 5, "Ucenik nije kaznjivan.");

INSERT INTO `mydb`.`Grad` VALUES (11320, "Velika Plana", "Republika Srbija");

INSERT INTO `mydb`.`Osoba` VALUES (123456, "Petar", "Petrovic", "m", "1995-06-16", "...", "petar123@gmail.com", 0652366854, 11320);
INSERT INTO `mydb`.`Osoba` VALUES (123455, "Marko", "Nedeljkovic", "m", "1975-01-11", "...", "nedeljkovic@gmail.com", 0645588741, 11320);
INSERT INTO `mydb`.`Osoba` VALUES (123433, "Mila", "Pavlovic", "z", "1985-06-18", "...", "milapavlovic@gmail.com", 0626698778, 11320);

INSERT INTO `mydb`.`Roditelj` VALUES (123433, "Ekonomista");

INSERT INTO `mydb`.`Skola` VALUES (999, "Nikola Tesla", "Tehnicka skola", "srednji nivo", 11320);

INSERT INTO `mydb`.`Odeljenje` VALUES (111, "IV-3", 4, 999);

INSERT INTO `mydb`.`Nastavnik` VALUES (123455, "Diplomirani inzenjer", 111);

INSERT INTO `mydb`.`Predmet` VALUES (2889, 60, "...", "...", "...", "...", 123455);

INSERT INTO `mydb`.`Smer` VALUES (554668, "Elektrotehnicar racunara", 999);

INSERT INTO `mydb`.`Ucenik` VALUES (123456, 223, 111, 554668);

INSERT INTO `mydb`.`JeDete` VALUES (123433, 123456);

INSERT INTO `mydb`.`DobioOcenu` VALUES (5, "2020-06-24", 123456, 2889);

INSERT INTO `mydb`.`Pohadja` VALUES (30, 15, 10, 123456, 2889);

/*Prikaz liste svih nastavnika sa predmetima koje oni drže*/
SELECT osoba.jmbg, osoba.ime, osoba.prezime, predmet.idPredmeta
FROM osoba INNER JOIN nastavnik ON osoba.jmbg = nastavnik.jmbgNastavnika
INNER JOIN predmet ON predmet.jmbgNastavnika = nastavnik.jmbgNastavnika;

/*Prikaz liste učenika i njihovih roditelja*/
SELECT R.J1 AS jmbgRoditelja, R.I1 AS imeRoditelja, R.P1 AS prezimeRoditelja, U.J2 AS jmbgUcenika, U.I2 AS imeUcenika, U.P2 AS prezimeUcenika
FROM jedete V
INNER JOIN (SELECT osoba.jmbg AS J1, osoba.ime AS I1, osoba.prezime AS P1 
FROM osoba INNER JOIN roditelj ON osoba.jmbg = roditelj.jmbgRoditelja) AS R
ON V.jmbgRoditelja = R.J1
INNER JOIN (SELECT osoba.jmbg AS J2, osoba.ime AS I2, osoba.prezime AS P2
FROM osoba INNER JOIN ucenik ON osoba.jmbg = ucenik.jmbgUcenika) AS U
ON V.jmbgUcenika = U.J2;

/*Prikaz liste škola sa njihovim smerovima*/
SELECT skola.idSkole , skola.nazivSkole, skola.tipSkole, skola.nivoSkole, smer.idSmera, smer.nazivSmera
FROM skola INNER JOIN smer ON skola.idSkole = smer.idSkole;

/*Prikaz liste jmbg brojeva učenika i id brojeve predmeta na koje idu, kao i jmbg brojeve nastavnika koje predaju te predmete*/
SELECT ucenik.jmbgUcenika, predmet.idPredmeta, nastavnik.jmbgNastavnika
FROM ucenik INNER JOIN pohadja ON ucenik.jmbgUcenika = pohadja.jmbgUcenika
INNER JOIN predmet ON pohadja.idPredmeta = predmet.idPredmeta
INNER JOIN nastavnik ON predmet.jmbgNastavnika = nastavnik.jmbgNastavnika;

/*Prikaz liste učenika i njihovih ocena iz nekog premeta*/
SELECT osoba.jmbg AS jmbgUcenika, osoba.ime AS imeUcenika, osoba.prezime AS prezimeUcenika, dobioocenu.idPredmeta, dobioocenu.ocena
FROM osoba INNER JOIN ucenik ON osoba.jmbg = ucenik.jmbgUcenika
INNER JOIN dobioocenu ON ucenik.jmbgUcenika = dobioocenu.jmbgUcenika;

/*Prikaz liste svih škola iz grada Velika Plana*/
SELECT skola.idSkole, skola.nazivSkole, skola.tipSkole, skola.nivoSkole, grd.nazivGrada FROM skola INNER JOIN
(SELECT ptt, nazivGrada FROM grad WHERE nazivGrada = "Velika Plana") AS grd
ON skola.ptt = grd.ptt;